export const FIND_LESSON_FOR_MODULE = "FIND_ALL_LESSONS"
export const CREATE_LESSON ="CREATE_LESSON"
export const DELETE_LESSON = "DELETE_LESSON"
export const SET_LESSON_TO_DEFAULT = "SET_LESSON_TO_DEFAULT"